apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: LoadBalancer
  externalIPs:
  - 172.20.3.90
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
