apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sts-redis-sentinel
spec:
  serviceName: "svc-redis-sentinel"
  replicas: 3
  template:
    metadata:
      labels:
        name: sts-redis-sentinel
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-sentinel
        image: inwinstack/redis:4.0.8
        imagePullPolicy: Always
        env:
        - name: SENTINEL
          value: "true"
        - name: MASTER_HOST
          value: sts-redis-master-0.svc-redis-master
        - name: MASTER_PORT
          value: "6379"
        - name: SENTINEL_HOST
          value: sts-redis-sentinel-0.svc-redis-sentinel
        - name: SENTINEL_PORT
          value: "26379"
        - name: SENTINEL_SVC
          value: svc-redis-sentinel
        ports:
        - containerPort: 26379
