apiVersion: v1
kind: Service
metadata:
  name: svc-redis-sentinel
  labels:
    name: svc-redis-sentinel
spec:
  ports:
  - port: 26379
    targetPort: 26379
  clusterIP: None
  selector:
    name: sts-redis-sentinel
