apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sts-redis-slave
spec:
  serviceName: "svc-redis-slave"
  replicas: 3
  template:
    metadata:
      labels:
        name: sts-redis-slave
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-slave
        image: inwinstack/redis:4.0.8
        imagePullPolicy: Always
        env:
        - name: SLAVE
          value: "true"
        - name: MASTER_HOST
          value: sts-redis-master-0.svc-redis-master
        - name: MASTER_PORT
          value: "6379"
        - name: SENTINEL_HOST
          value: sts-redis-sentinel-0.svc-redis-sentinel
        - name: SENTINEL_PORT
          value: "26379"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redisslave
          mountPath: /data/redis
        securityContext:
          capabilities: {}
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: redisslave
    spec:
      storageClassName: rbd
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
