apiVersion: v1
kind: Pod
metadata:
  name: rbd-mount-pod
spec:
  containers:
  - name: rbd-mount-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "while :; do touch /mnt/SUCCESS; sleep 15; done"
    volumeMounts:
      - name: rbd
        mountPath: "/mnt/"
  restartPolicy: "Never"
  volumes:
    - name: rbd
      rbd:
        monitors:
        - ceph-mon.ceph:6789
        user: admin
        image: rbd-pod
        pool: rbd
        fsType: ext4
        secretRef:
          name: ceph-client-secret
