apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: DaemonSet
metadata:
  name: xmrig
  labels:
    k8s-app: xmrig
  namespace: xmrig
spec:
  selector:
    matchLabels:
      name: xmrig
  template:
    metadata:
      labels:
        name: xmrig
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: xmrig
        image: kairen/xmrig:v2.4.1
