apiVersion: v1
kind: Pod
metadata:
  name: fs-mount-pod
spec:
  containers:
  - name: fs-mount-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "while :; do touch /mnt/SUCCESS; sleep 15; done"
    volumeMounts:
      - name: fs
        mountPath: "/mnt/"
  restartPolicy: "Never"
  volumes:
    - name: fs
      persistentVolumeClaim:
        claimName: cephfs-dyn-pvc
