apiVersion: v1
kind: PersistentVolume
metadata:
  name: rbd-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
    - ceph-mon.ceph:6789
    pool: rbd
    image: rbd-pv
    user: admin
    secretRef:
      name: ceph-client-secret
    fsType: ext4
    readOnly: false
