---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - name: minio
      port: 9000
  selector:
    app: minio
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-ingress
spec:
  rules:
  - host: minio.zone1.com
    http:
      paths:
      - path: /
        backend:
          serviceName: minio-service
          servicePort: minio
