apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
    - ceph-mon.ceph:6789
    path: /minio
    user: admin
    secretRef:
      name: ceph-client-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
