apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: outside
      targetPort: 9094
      port: 32400
      protocol: TCP
  selector:
    app: kafka
  type: LoadBalancer
  externalIPs:
  - 172.22.132.50
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  ports:
    - name: inside
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka
  type: ClusterIP
  clusterIP: None
