apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
       - name: volume-mount-hack
         image: busybox
         command: ["sh", "-c", "chown -R 1001:1001 /var/lib/kafka/"]
         volumeMounts:
           - name: kafka-storage
             mountPath: /var/lib/kafka/
      containers:
        - name: kafka
          image: kairen/kafka:1.0.1
          env:
            - name: ADVERTISED_ADDRESS
              value: "172.22.132.50:32400"
          ports:
            - name: inside
              containerPort: 9092
              protocol: TCP
            - name: outside
              containerPort: 9094
            - name: jmx
              containerPort: 5555
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        storageClassName: rbd
        resources:
          requests:
            storage: 10Gi
        accessModes: [ "ReadWriteOnce" ]
